DAY=09

create_day_folder:
	mkdir ${DAY}


add_empty_input_files:
	touch ${DAY}/example.txt
	touch ${DAY}/input.txt

create: create_day_folder add_empty_input_files
	cp template/main.js ${DAY}/main.js
